### ISSUE TITLE
Exercises tracking issue

### ISSUE THREAD

**Issue by gr2m** [gr2m/advanced-react-hooks#1]
- [ ] Advanced React Hooks Welcome
- [ ] useReducer: simple Counter
- [ ] useCallback: custom hooks
- [ ] useContext: simple Counter
- [ ] useLayoutEffect: auto-growing textarea
- [ ] useImperativeHandle: scroll to top/bottom
- [ ] useDebugValue: useMedia
- [ ] Advanced React Hooks Outro

**Comment by gr2m** [comment]
Note to self and others interested, here is how I setup this repository using the [GitHub CLI](https://cli.github.com/)

This command will create a new `advanced-react-hooks` folder in the current directory and setup git.

```
gh repo fork kentcdodds/advanced-react-hooks
```

Change directory into `advanced-react-hooks` and run the setup script

```
cd advanced-react-hooks
node setup
```

Remove the `.github/workflows/validate.yml` workflow. Add [`.github/workflows/test.yml`](https://github.com/gr2m/advanced-react-hooks/blob/7d1c11277bbdd03a1976eaf07d3e58b6a2cf73ed/.github/workflows/test.yml) instead. Commit and push the change. This will add proper CI to your pull requests :)

Now go to the repositorie's Actions tab and enable actions.

Enable issues in your fork's settings, then create a tracking issue with all excercises:

```md
- [ ] useState: greeting
- [ ] useEffect: persistent state
- [ ] Hooks Flow
- [ ] Lifting state
- [ ] useState: tic tac toe
- [ ] useRef and useEffect: DOM interaction
- [ ] useEffect: HTTP requests
```

Create an issue for each exercise as I get there. Then create a pull request once I finish the exercise. Example: #3

Rinse & repeat until all exercises are done 🎉
